export const COURSES_DATA = [
    {
      id: '1',
      title: 'HTML & CSS Fundamentals',
      description: 'Learn the building blocks of the web. Master HTML structure and CSS styling.',
      icon: '🌐',
      color: '#E44D26',
      level: 'Beginner',
      duration: '4 hours',
      lessons: [
        { id: 'l1', title: 'What is HTML?', duration: '10 min', content: 'HTML (HyperText Markup Language) is the standard language for creating web pages. It describes the structure of a web page using markup.\n\nHTML elements are the building blocks of HTML pages. They are represented by tags like <html>, <head>, <body>, <h1>, <p>, etc.\n\nExample:\n```html\n<!DOCTYPE html>\n<html>\n  <head>\n    <title>My First Page</title>\n  </head>\n  <body>\n    <h1>Hello World!</h1>\n    <p>This is my first web page.</p>\n  </body>\n</html>\n```' },
        { id: 'l2', title: 'HTML Tags & Elements', duration: '12 min', content: 'HTML tags are keywords surrounded by angle brackets. Most tags come in pairs: an opening tag and a closing tag.\n\nCommon HTML tags:\n- <h1> to <h6>: Headings\n- <p>: Paragraph\n- <a>: Anchor/Link\n- <img>: Image\n- <div>: Division\n- <span>: Inline container\n- <ul>, <ol>, <li>: Lists\n\nExample:\n```html\n<h1>Main Heading</h1>\n<p>A paragraph of text.</p>\n<a href="https://example.com">Click here</a>\n<img src="photo.jpg" alt="A photo">\n```' },
        { id: 'l3', title: 'CSS Basics', duration: '15 min', content: 'CSS (Cascading Style Sheets) controls the visual presentation of HTML elements.\n\nCSS Syntax:\n```css\nselector {\n  property: value;\n}\n```\n\nWays to add CSS:\n1. Inline: <p style="color: red;">\n2. Internal: <style> tag in <head>\n3. External: separate .css file\n\nExample:\n```css\nbody {\n  background-color: #f0f0f0;\n  font-family: Arial, sans-serif;\n}\n\nh1 {\n  color: purple;\n  font-size: 32px;\n}\n```' },
        { id: 'l4', title: 'CSS Flexbox', duration: '20 min', content: 'Flexbox is a CSS layout model that makes it easy to design flexible and responsive layouts.\n\nKey properties:\n```css\n.container {\n  display: flex;\n  justify-content: center; /* horizontal alignment */\n  align-items: center;     /* vertical alignment */\n  gap: 16px;               /* space between items */\n  flex-direction: row;     /* or column */\n}\n```\n\nFlex children:\n```css\n.item {\n  flex: 1;  /* grow to fill space */\n}\n```' },
      ],
      quiz: [
        { id: 'q1', question: 'What does HTML stand for?', options: ['HyperText Markup Language', 'High Tech Modern Language', 'HyperText Modern Links', 'Hyper Transfer Markup Language'], answer: 0 },
        { id: 'q2', question: 'Which tag is used for the largest heading?', options: ['<h6>', '<heading>', '<h1>', '<head>'], answer: 2 },
        { id: 'q3', question: 'What does CSS stand for?', options: ['Creative Style Sheets', 'Cascading Style Sheets', 'Computer Style Sheets', 'Colorful Style Sheets'], answer: 1 },
        { id: 'q4', question: 'Which CSS property controls text color?', options: ['text-color', 'font-color', 'color', 'foreground'], answer: 2 },
        { id: 'q5', question: 'What is the correct CSS display value for flexbox?', options: ['display: block', 'display: flex', 'display: grid', 'display: inline'], answer: 1 },
      ],
    },
    {
      id: '2',
      title: 'JavaScript Basics',
      description: 'Master the programming language of the web. Learn variables, functions, and more.',
      icon: '⚡',
      color: '#F7DF1E',
      level: 'Beginner',
      duration: '6 hours',
      lessons: [
        { id: 'l1', title: 'Variables & Data Types', duration: '15 min', content: 'JavaScript has three ways to declare variables:\n\n```javascript\nvar name = "John";    // old way\nlet age = 25;         // block-scoped\nconst PI = 3.14;      // constant\n```\n\nData types:\n- String: "Hello"\n- Number: 42, 3.14\n- Boolean: true, false\n- Array: [1, 2, 3]\n- Object: { key: "value" }\n- null, undefined' },
        { id: 'l2', title: 'Functions', duration: '18 min', content: 'Functions are reusable blocks of code.\n\n```javascript\n// Function declaration\nfunction greet(name) {\n  return "Hello, " + name;\n}\n\n// Arrow function\nconst greet = (name) => {\n  return `Hello, ${name}`;\n};\n\n// Short arrow function\nconst greet = name => `Hello, ${name}`;\n\n// Call the function\ngreet("Karya"); // "Hello, Karya"\n```' },
        { id: 'l3', title: 'Arrays & Objects', duration: '20 min', content: 'Arrays store ordered lists. Objects store key-value pairs.\n\n```javascript\n// Arrays\nconst fruits = ["apple", "banana", "mango"];\nfruits.push("grape");      // add\nfruits.pop();              // remove last\nfruits.length;             // 3\n\n// Array methods\nfruits.map(f => f.toUpperCase());\nfruits.filter(f => f.length > 5);\n\n// Objects\nconst user = {\n  name: "Karya",\n  age: 20,\n  greet() { return "Hi!" }\n};\nuser.name;     // "Karya"\nuser["age"];   // 20\n```' },
        { id: 'l4', title: 'Async & Promises', duration: '25 min', content: 'JavaScript handles async operations with Promises and async/await.\n\n```javascript\n// Promise\nfetch("https://api.example.com/data")\n  .then(res => res.json())\n  .then(data => console.log(data))\n  .catch(err => console.error(err));\n\n// async/await (cleaner)\nasync function getData() {\n  try {\n    const res = await fetch("https://api.example.com/data");\n    const data = await res.json();\n    return data;\n  } catch (err) {\n    console.error(err);\n  }\n}\n```' },
      ],
      quiz: [
        { id: 'q1', question: 'Which keyword creates a constant variable?', options: ['var', 'let', 'const', 'static'], answer: 2 },
        { id: 'q2', question: 'What does the arrow function => do?', options: ['Creates a class', 'Defines a function', 'Imports a module', 'Creates an object'], answer: 1 },
        { id: 'q3', question: 'Which method adds an item to the END of an array?', options: ['push()', 'pop()', 'shift()', 'unshift()'], answer: 0 },
        { id: 'q4', question: 'What does async/await help with?', options: ['Styling', 'Asynchronous code', 'Database queries only', 'HTML structure'], answer: 1 },
        { id: 'q5', question: 'What is the output of: typeof "hello"?', options: ['"text"', '"word"', '"string"', '"char"'], answer: 2 },
      ],
    },
    {
      id: '3',
      title: 'React Native',
      description: 'Build cross-platform mobile apps using React Native and JavaScript.',
      icon: '⚛️',
      color: '#61DAFB',
      level: 'Intermediate',
      duration: '8 hours',
      lessons: [
        { id: 'l1', title: 'What is React Native?', duration: '10 min', content: 'React Native lets you build mobile apps using JavaScript and React. It compiles to native iOS and Android code.\n\nKey concepts:\n- Components: building blocks of UI\n- Props: data passed to components\n- State: dynamic data inside components\n\nBasic component:\n```javascript\nimport { View, Text, StyleSheet } from "react-native";\n\nexport default function App() {\n  return (\n    <View style={styles.container}>\n      <Text>Hello KaryaChat!</Text>\n    </View>\n  );\n}\n```' },
        { id: 'l2', title: 'Core Components', duration: '20 min', content: 'React Native has built-in components:\n\n```javascript\nimport {\n  View,        // like <div>\n  Text,        // like <p>\n  TextInput,   // like <input>\n  TouchableOpacity, // button\n  ScrollView,  // scrollable container\n  FlatList,    // optimized list\n  Image,       // display images\n  StyleSheet,  // styling\n} from "react-native";\n```' },
        { id: 'l3', title: 'useState & useEffect', duration: '22 min', content: 'Hooks manage state and side effects.\n\n```javascript\nimport { useState, useEffect } from "react";\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n\n  useEffect(() => {\n    console.log("Count changed:", count);\n  }, [count]);\n\n  return (\n    <TouchableOpacity onPress={() => setCount(count + 1)}>\n      <Text>Count: {count}</Text>\n    </TouchableOpacity>\n  );\n}\n```' },
      ],
      quiz: [
        { id: 'q1', question: 'React Native compiles to which platforms?', options: ['Web only', 'iOS only', 'iOS and Android', 'Windows only'], answer: 2 },
        { id: 'q2', question: 'Which component is like a <div> in React Native?', options: ['Box', 'View', 'Container', 'Frame'], answer: 1 },
        { id: 'q3', question: 'Which hook manages component state?', options: ['useEffect', 'useRef', 'useState', 'useContext'], answer: 2 },
        { id: 'q4', question: 'What is the optimized list component in React Native?', options: ['ScrollView', 'ListView', 'FlatList', 'MapView'], answer: 2 },
        { id: 'q5', question: 'What does useEffect with [] dependency run?', options: ['On every render', 'Only on mount', 'Never', 'Only on unmount'], answer: 1 },
      ],
    },
  ];